name: "Kavita"
version: 0.9.0
slug: "Kavita"
description: "Kavita is a media server for your comics, mangas, BDs, magazines and eBooks."
url: https://wiki.kavitareader.com/getting-started/
arch:
  - amd64
  - aarch64
  - armhf
  - i386
  - armv7
ports:
  5000/tcp: 5000
map:
  - type: addon_config
    read_only: false
  - type: media
    read_only: False
  - type: share
    read_only: false
image: "ghcr.io/kareadita/kavita:0.9.0"
